spring:
  datasource:
    url: jdbc:mysql://192.168.0.5:3306/mydb
    username: myuser
    password: dbsdud12
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.0.5
      port: 6379
  session:
    timeout: 5m
    redis:
      namespace: "spring:"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
security:
  remember-me:
    key: rememberMeKey
    duration: 1209600
