server:
  port: ${PORT}
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  session:
    timeout: 5m
    redis:
      namespace: "spring:"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
              - openid